name = "Peridynamics"
uuid = "4dc47793-80f3-4232-b30e-ca78ca9d621b"
authors = ["Kai Friebertsh√§user"]
version = "0.1.0"

[deps]
AbaqusReader = "bc6b9049-e460-56d6-94b4-a597b2c0390d"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
julia = "1.7"
AbaqusReader = "0.2"
FileIO = "1"
JLD2 = "0.4"
ProgressMeter = "1"
StaticArrays = "1"
WriteVTK = "1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
