name = "Peridynamics"
uuid = "4dc47793-80f3-4232-b30e-ca78ca9d621b"
authors = ["Kai Partmann"]
version = "0.1.1"

[deps]
AbaqusReader = "bc6b9049-e460-56d6-94b4-a597b2c0390d"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
AbaqusReader = "0.2"
CodecZlib = "0.7"
LightXML = "0.9"
ProgressMeter = "1"
StaticArrays = "1"
WriteVTK = "1"
julia = "1.7"

