name = "Peridynamics"
uuid = "4dc47793-80f3-4232-b30e-ca78ca9d621b"
authors = ["Kai Partmann"]
version = "0.4.0"

[deps]
AbaqusReader = "bc6b9049-e460-56d6-94b4-a597b2c0390d"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PointNeighbors = "1c4d5385-0a27-49de-8e2c-43b175c8985c"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
AbaqusReader = "0.2"
Base64 = "1.8"
CodecZlib = "0.7"
Dates = "1.8"
LibGit2 = "1.8"
LightXML = "0.9"
LinearAlgebra = "1.8"
MPI = "0.20.0"
PointNeighbors = "0.4.5, 0.5, 0.6"
PrecompileTools = "1.0"
Printf = "1.8"
ProgressMeter = "1.0"
StaticArrays = "1.0"
ThreadPinning = "0.7, 1"
TimerOutputs = "0.5"
WriteVTK = "1.19"
julia = "1.10"
